-- TABLE PROEJCTS

CREATE TABLE projects(
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(150) DEFAULT NULL,
  description VARCHAR(250) DEFAULT NULL,
  liveDemoUrl VARCHAR(150) DEFAULT NULL,
	imageUrl VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (id)
);